name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 4: Build the project
      - name: Build the project
        run: yarn build

      # Step 5: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts 
          path: dist/ 

# Step 5: Deploy to another repository
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://github.com/LightWave-HQ/Lightwave.git target-repo
          cd target-repo
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/LightWave-HQ/Lightwave.git
          rm -rf data/*
          cp -r ../dist/* data/
          git add --all
          git commit -m "Deploy built files [$(date)]" || echo "No changes to commit"
          git push origin main